**Оцінювання даної роботи буде ураховувати якість Вашого коду та текстових відповідей. При наявності ЛИШЕ коду , робота оцінюватися НЕ БУДЕ.**  

**Оформлення текстових відповідей повинно проводитися в текстових комірках ноутбука з використанням синтаксису [LaTeX](https://en.wikibooks.org/wiki/LaTeX/Basics) для оформлення тексту та формул.**

**Роботи ідентифіковані як ІДЕНТИЧНІ одразу отримують 0 балів.**

**При реалізації завдань потрібно використовувати методи з бібліотеки numpy та pandas.**

**Рішення з циклами будуть оцінені в 0 балів.**

# I. NumPy.

0. Імпортувати numpy загальноприйнятим способом.

In [3]:
import numpy as np

1. Визначити список з оцінками студента(ки) за семестр. Використовуючи його, створити одновимірний масив numpy.

In [4]:
grades = [51, 58, 88, 72, 79, 60, 100]
grades_list = np.array(grades)
print(grades_list)

[ 51  58  88  72  79  60 100]


2. Визначити список зі списками, де кожен рядок списку формально означає магазин, а кожна колонка - певний продукт (батон, яйця першої категорії, молоко та ковбаса), а елементами на пересічі є ціни на ці продукти відповідно. Використовуючи цей список, створити матрицю (двовимірний масив) numpy.

In [5]:
prices = [
    [14.4, 11.0, 21.2, 44.6], 
    [13.8, 10.7, 20.8, 45.0], 
    [15.0, 11.4, 21.0, 43.7] 
]
price_matrix = np.array(prices)
print("Price matrix:\n", price_matrix)

Price matrix:
 [[14.4 11.  21.2 44.6]
 [13.8 10.7 20.8 45. ]
 [15.  11.4 21.  43.7]]


3. Отримайте тип даних значень з масивів завдань 2 та 3. Виведіть їх на екран.

In [6]:
print("grades list data type:", grades_list.dtype)
print("matrix prices data type:", price_matrix.dtype)


grades list data type: int64
matrix prices data type: float64


4. Отримайте форми (кортеж з кількістю рядків та колонок) масивів завдань 2 та 3. Виведіть їх на екран.

In [7]:
print("grades list shape:", grades_list.shape)
print("matrix prices shape:", price_matrix.shape)


grades list shape: (7,)
matrix prices shape: (3, 4)


5. Створіть одновимірний масив за допомогою спеціальної функції numpy, який би відображав динаміку стабільно зростаючого (з рівними проміжками) прибутку з продажів  за тиждень, де у перший день не було продажів, а в останній день тижня вдалося заробити 1000 грн 50 коп.

In [8]:
sales_profit = np.linspace(0, 1000.5, 7)
print("dynamic of week profit:", sales_profit)

dynamic of week profit: [   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]


6. Створіть два масиви. Використовуючи їх, продемонструйте відмінність вертикального та горизонтального обʼєднання масивів.

In [9]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
horizontal_merge = np.hstack((array1, array2))
vertical_merge = np.vstack((array1, array2))
print("horizontal merge:", horizontal_merge)
print("vertical merge:\n", vertical_merge)


horizontal merge: [1 2 3 4 5 6]
vertical merge:
 [[1 2 3]
 [4 5 6]]


7. Визначити функцію, яка приймає на вході масив і транспонує його. Скористайтесь методом reshape. І не забудьте почати з docstrings.

In [10]:
def transpose_array(arr):
    """
    Функція для транспонування масиву за допомогою reshape.
    
    Parameters:
    arr (numpy.ndarray): Масив, який потрібно транспонувати.
    
    Returns:
    numpy.ndarray: Транспонований масив.
    """
    return arr.reshape(arr.shape[::-1])

original_matrix = np.array([[1, 2, 3], [4, 5, 6]])
transposed = transpose_array(original_matrix)
print("Original matrix:\n", original_matrix)
print("Transposed matrix:\n", transposed)

Original matrix:
 [[1 2 3]
 [4 5 6]]
Transposed matrix:
 [[1 2]
 [3 4]
 [5 6]]


8. Створіть два масиви. Використовучи ці масиви, продемонструйте 1) операцію по-елементного додавання, 2) операцію по-елементного віднімання, 3) множення масиву на число, 4) операцію по-елементного множення, і 5) матричного множення.

In [11]:
matrix1 = np.array([
[8, 3, 11],
[54, 1, 90],
[89, 65, 34]
])

matrix2= np.array([
[18, 13, 51],
[14, 8, 60],
[45, 78, 66]
])

print(matrix1 + matrix2, '\n') 
print(matrix1 - matrix2, '\n')
print(matrix1 * 2 , '\n')
print(matrix1 * matrix2, '\n')
print(np.dot(matrix1, matrix2) ) 



[[ 26  16  62]
 [ 68   9 150]
 [134 143 100]] 

[[-10 -10 -40]
 [ 40  -7  30]
 [ 44 -13 -32]] 

[[ 16   6  22]
 [108   2 180]
 [178 130  68]] 

[[ 144   39  561]
 [ 756    8 5400]
 [4005 5070 2244]] 

[[  681   986  1314]
 [ 5036  7730  8754]
 [ 4042  4329 10683]]


9. Створіть двовимірний масив (матрицю) та розрахуйте: 1) мінімальне число, 2) максимальне число, 3) суму чисел, 4) мінімальні числа для кожного рядка, 5) максимальні числа для кожного стовпчика.

In [12]:
matrix = np.array([
[8, 3, 11],
[54, 1, 90],
[89, 65, 34]
])

min_value = np.min(matrix)
print("min value: ", min_value)

max_value = np.max(matrix)
print("max value: ", max_value)

sum = np.sum(matrix)
print("sum: ", sum)

min_row_value = np.min(matrix, axis = 1)
print("min value per row: " , min_row_value)

max_column_value = np.max(matrix, axis = 0)
print("max value per column: " , max_column_value)

min value:  1
max value:  90
sum:  355
min value per row:  [ 3  1 34]
max value per column:  [89 65 90]


10. Створіть матрицю , де деякі елементи повторюються. Знайдіть унікальні значення елементів цієї матриці та їхні частоти.

In [13]:
matrix = np.array([
[8, 3, 8],
[54, 1, 90],
[8, 65, 8]
])

unique_value, frequencies = np.unique(matrix, return_counts=True)
print(unique_value)
print(frequencies)

[ 1  3  8 54 65 90]
[1 1 4 1 1 1]


# II. Importing. Creating DF

0. Імпортувати бібліотеку pandas

In [14]:
import pandas as pd

11. Створити тестовий датафрейм зі списку, що містить записи пацієнтів про їхні прізвища, імена, дату народження, масу тіла та наявність медичного страхування. Одне зі значень зробить пустим. Ознайомтесь з типом кожної колонки.

In [15]:

data = [
    {"Last Name": "Smith", "First Name": "John", "Date of Birth": "1990-01-15", "Weight": 75.5, "Health Insurance": True},
    {"Last Name": "Johnson", "First Name": "Mike", "Date of Birth": "1985-06-20", "Weight": 82.3, "Health Insurance": False},
    {"Last Name": "Brown", "First Name": "Linda", "Date of Birth": "1992-12-01", "Weight": None, "Health Insurance": True},
    {"Last Name": "Taylor", "First Name": "Emma", "Date of Birth": "1978-03-10", "Weight": 90.0, "Health Insurance": True}
]

dataframe = pd.DataFrame(data)

print("dataframe:")
print(dataframe)

print("\nrow types:")
print(dataframe.dtypes)


dataframe:
  Last Name First Name Date of Birth  Weight  Health Insurance
0     Smith       John    1990-01-15    75.5              True
1   Johnson       Mike    1985-06-20    82.3             False
2     Brown      Linda    1992-12-01     NaN              True
3    Taylor       Emma    1978-03-10    90.0              True

row types:
Last Name            object
First Name           object
Date of Birth        object
Weight              float64
Health Insurance       bool
dtype: object


# III. Reading from file

12. Завантажити файл missile_attacks_daily.csv з [Kaggle](https://www.kaggle.com/datasets/piterfm/massive-missile-attacks-on-ukraine?select=missile_attacks_daily.csv). Ознайомитись з описом датасету. Додати файл до папки поточної сесії colab notebook на панелі ліворуч або на гугл диск (локально до проєкту, якщо працюєте у пайчармі). Зчитати датафрейм з файлу та вивести датафрейм на екран. Зверніть увагу на те, щоб всі колонки відповідали наведеним у описі типам даних.

In [16]:
file_path = './missile_attacks_daily.csv'  
dataframe = pd.read_csv(file_path)


print(dataframe.head())


print(dataframe.info())

         time_start          time_end           model  \
0  2025-01-25 19:00  2025-01-26 09:00  Shahed-136/131   
1  2025-01-24 19:00  2025-01-25 09:30  Shahed-136/131   
2  2025-01-24 18:30  2025-01-24 19:30       X-59/X-69   
3  2025-01-23 21:00  2025-01-24 09:00  Shahed-136/131   
4  2025-01-22 19:00  2025-01-23 09:30  Shahed-136/131   

                                        launch_place        target carrier  \
0  Primorsko-Akhtarsk and Kursk oblast and Bryans...       Ukraine     NaN   
1  Primorsko-Akhtarsk and Kursk oblast and Bryans...       Ukraine     NaN   
2                                          Black Sea  Odesa oblast     NaN   
3  Primorsko-Akhtarsk and Kursk oblast and Bryans...       Ukraine     NaN   
4  Primorsko-Akhtarsk and Kursk oblast and Bryans...       Ukraine     NaN   

   launched  destroyed  not_reach_goal  cross_border_belarus  back_russia  \
0      72.0         50             9.0                   NaN          NaN   
1      61.0         46            

# IV. Data understanding

13. Виведіть на екран перші 10 рядків зчитаного датафрейму.

In [17]:
print(dataframe.head(10))

         time_start          time_end             model  \
0  2025-01-25 19:00  2025-01-26 09:00    Shahed-136/131   
1  2025-01-24 19:00  2025-01-25 09:30    Shahed-136/131   
2  2025-01-24 18:30  2025-01-24 19:30         X-59/X-69   
3  2025-01-23 21:00  2025-01-24 09:00    Shahed-136/131   
4  2025-01-22 19:00  2025-01-23 09:30    Shahed-136/131   
5  2025-01-23 04:00  2025-01-23 04:30  Iskander-M/KN-23   
6  2025-01-21 19:00  2025-01-22 10:00    Shahed-136/131   
7  2025-01-20 20:00  2025-01-21 09:00    Shahed-136/131   
8  2025-01-20 20:00  2025-01-21 09:00        Iskander-M   
9  2025-01-19 19:00  2025-01-20 08:00    Shahed-136/131   

                                        launch_place        target carrier  \
0  Primorsko-Akhtarsk and Kursk oblast and Bryans...       Ukraine     NaN   
1  Primorsko-Akhtarsk and Kursk oblast and Bryans...       Ukraine     NaN   
2                                          Black Sea  Odesa oblast     NaN   
3  Primorsko-Akhtarsk and Kursk oblast

14. Отримайте інформацію про форму датафрейму.

In [18]:
print(dataframe.shape)

(2056, 16)


15. Отримайте дані про кожну колонку з її назвою, типом даних та кількістю непустих значень.

In [19]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2056 entries, 0 to 2055
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   time_start            2056 non-null   object 
 1   time_end              2056 non-null   object 
 2   model                 2056 non-null   object 
 3   launch_place          1034 non-null   object 
 4   target                2028 non-null   object 
 5   carrier               225 non-null    object 
 6   launched              2053 non-null   float64
 7   destroyed             2056 non-null   int64  
 8   not_reach_goal        164 non-null    float64
 9   cross_border_belarus  32 non-null     float64
 10  back_russia           35 non-null     float64
 11  still_attacking       30 non-null     float64
 12  destroyed_details     301 non-null    object 
 13  launched_details      4 non-null      object 
 14  launch_place_details  4 non-null      object 
 15  source               

16. Отримайте статистику для колонок числового типу.

In [20]:
dataframe.describe()

,launched,destroyed,not_reach_goal,cross_border_belarus,back_russia,still_attacking
count,2053.000000,2056.000000,164.000000,32.000000,35.000000,30.000000
mean,10.872382,7.647860,21.231707,2.312500,2.000000,2.766667
std,21.605295,14.506397,19.812804,2.054696,1.137593,2.848876
min,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,1.000000,1.000000,4.000000,1.000000,1.000000,1.000000
50%,2.000000,1.000000,16.000000,2.000000,2.000000,1.000000
75%,9.000000,7.000000,30.000000,2.000000,3.000000,3.750000
max,193.000000,99.000000,105.000000,10.000000,5.000000,10.000000


17. Отримати кількість унікальних значень у кожній колонці. Вивести на екран значення та кількість цих значень у колонці, яка має найменше унікальних значень.

In [21]:
unique_counts = dataframe.nunique()

min_unique_column = unique_counts.idxmin()


print(f"column with min uniq values: {min_unique_column}")
print(dataframe[min_unique_column].value_counts())

column with min uniq values: launched_details
launched_details
{'X-101/X-555': 50, 'Kalibr': 12}                     1
{'X-101/X-555': 55, 'Kalibr': 24, 'Iskander-K': 7}    1
{'X-101/X-555': 57, 'Kalibr': 28}                     1
{'X-101/X-555': 77, 'Kalibr': 28, 'X-59/X-69': 10}    1
Name: count, dtype: int64


18. На основі отриманої інформації про датасет вище, опишіть по пунктах, що б ви виправили або на що б звернули увагу на кроці очищення даних і чому?

**місце для текстової відповіді**

1. Dublicates
2. big amount of NaNs

...


# V. Data Cleaning

19. Перетворити колонку launched у цілочислену (Int64). Перевірити, чи все пройшло, як очікувалось.

In [22]:
dataframe['launched'] = dataframe['launched'].astype('Int64')

print(dataframe['launched'].dtype)

Int64


20. Видалити колонки, де кількість непустих значень становить менше 30% від загальної кількості записів.

In [23]:
not_null_counter = dataframe.notnull().sum()

rows_amount = len(dataframe)

min_not_null_count = rows_amount * 0.3

useless_columns = not_null_counter[not_null_counter < min_not_null_count].index

dataframe.drop(columns=useless_columns, inplace=True)

print(dataframe.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2056 entries, 0 to 2055
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   time_start    2056 non-null   object
 1   time_end      2056 non-null   object
 2   model         2056 non-null   object
 3   launch_place  1034 non-null   object
 4   target        2028 non-null   object
 5   launched      2053 non-null   Int64 
 6   destroyed     2056 non-null   int64 
 7   source        2056 non-null   object
dtypes: Int64(1), int64(1), object(6)
memory usage: 130.6+ KB
None


21. Очистити датафрейм від дублікатів (дублюючихся рядків) та записів, де атака продовжувалась відʼємну або нульову кількість часу (що фізично неможливо). Не забудьте оновити індекс. Скільки рядків було видалено? Як ви це перевірили у коді?

In [24]:

start_row_amount = len(dataframe)

dataframe['time_start'] = pd.to_datetime(dataframe['time_start'], errors='coerce')
dataframe['time_end'] = pd.to_datetime(dataframe['time_end'], errors='coerce')
dataframe['attack_duration'] = (dataframe['time_end'] - dataframe['time_start']).dt.total_seconds()
dataframe_without_duplicates = dataframe.drop_duplicates()
dataframe_without_duplicates = dataframe_without_duplicates[dataframe_without_duplicates['attack_duration'] > 0]
dataframe_without_duplicates.reset_index(drop=True, inplace=True)

new_row_count = len(dataframe_without_duplicates)
rows_deleted = start_row_amount - new_row_count
print(f"rows deleted: {rows_deleted}")


rows deleted: 1611


Кількість видалених рядків це різниця між початковою кількістю рядків та кількістю рядків після очищення від дублікатів і іншого мусору.

22. Виведіть на екран всі рядки, де є хоч одне пропущене значення.

In [25]:
rows_with_NaN = dataframe[dataframe.isnull().any(axis=1)]
print(rows_with_NaN)


              time_start            time_end               model launch_place  \
11                   NaT                 NaT            Orlan-10          NaN   
24                   NaT                 NaT                ZALA          NaN   
25                   NaT                 NaT            Supercam          NaN   
26                   NaT                 NaT            Orlan-10          NaN   
27                   NaT                 NaT              Lancet          NaN   
...                  ...                 ...                 ...          ...   
2051 2022-10-01 12:00:00 2022-10-01 12:00:00            Orlan-10          NaN   
2052                 NaT                 NaT            Orlan-10          NaN   
2053 2022-09-29 23:00:00 2022-09-29 23:59:00      Shahed-136/131          NaN   
2054                 NaT                 NaT                X-59          NaN   
2055                 NaT                 NaT  Reconnaissance UAV          NaN   

                           